# Generated by Django 3.2.9 on 2022-03-25 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_listed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
