# Generated by Django 3.2.9 on 2022-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_date_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='headphones', max_length=100),
            preserve_default=False,
        ),
    ]
