# Generated by Django 3.2.9 on 2022-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderItemTotal',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderTotal',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
