# Generated by Django 3.2.9 on 2022-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220405_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderTotal',
        ),
        migrations.AddField(
            model_name='order',
            name='orderTotal',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
