# Generated by Django 3.2.9 on 2022-04-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220405_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderItemTotal',
        ),
    ]
