# Generated by Django 3.2.9 on 2022-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_ordertotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderItemTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
